### ISSUE TITLE
base name

### ISSUE THREAD

**Issue by r00bal** [AdamczukPawel/goit-react-hw-05-movies#1]
https://github.com/AdamczukPawel/goit-react-hw-05-movies/blob/d7fd4b7967d4de10a53db6e0999db27e08ec131e/src/index.js#L8

Twoja strona osadzona jest na https://AdamczukPawel.github.io/goit-react-hw-05-movies/ ale nigdzie nie uwzględniasz /goit-react-hw-05-movies/ do którego powinny być doklejane kolejne ścieżki. Jak zrobisz odśwież stronę w trakcie przeglądania aplikacji to dostaniesz site not found a powinieneś zostać w miejscu gdzie skończyłeś przeglądanie.
Możesz ten base url ustawić tutaj

<BrowserRouter basename="/goit-react-hw-05-movies">
      <App />

**Comment by AdamczukPawel** [comment]
Done
