### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by r00bal** [AdamczukPawel/goit-react-hw-05-movies#2]
https://github.com/AdamczukPawel/goit-react-hw-05-movies/blob/d7fd4b7967d4de10a53db6e0999db27e08ec131e/src/pages/Movies/MovieDetails/MovieDetails.js#L64-L67

Przycisk goBack nie działa poprawnie z cast i review zapewne dlatego, że nie przekazujesz tutaj stanu, kiedy odwołamy się do niego w
 `const backLinkHref = location.state?.from ?? '/';`
dostaniemy undefined i backLinkHref przyjmie wartość '/' i wrócimy na home page.

Żeby przycisk go back działał poprawnie  to musimy tutaj -> 
1) albo przekazać stan ten wcześniejszy ` state={{ moviesList: location.state.moviesList }}` albo nowy  `state={{ moviesList: location }}`
2) ewentulanie skorzystać z wersji uproszczonej, która zawsze cofnie nas o jedną akcje wstecz ze stosu historii, przy pomocy hooka useNavigate() np.:
```
const navigate = useNavigate();
onCLick={() =>  navigate(-1)}
```

**Comment by AdamczukPawel** [comment]
Done
